pub use communication::serial_protocol::SerialProtocolStub;
pub use communication::event_bus_stub::EventBusStub;
pub mod multi_mcu_manager;
pub use multi_mcu_manager::MultiMCUManagerStub;
pub mod module_manager;
pub use module_manager::ModuleManagerStub;
// lib.rs for krusty-rs: expose modules for benchmarks and external use
pub mod config;
pub use config::*;
pub use config::Config;
pub use config::MotionConfig;
pub mod gcode;
pub use krusty_shared::gcode::{GCodeCommand, GCodeParser, GCodeParserConfig, MacroProcessor};
// pub mod print_job; // migrated to krusty_shared or handled via direct use
pub mod file_manager;
pub use file_manager::*;
pub mod host_os;
pub use crate::host_os::PrinterHostOS;
pub use host_os::PrinterState;
pub mod system_info;
pub use krusty_shared::system_info::SystemInfo;
pub mod motion;
pub use motion::*;
pub use krusty_shared::trajectory::MotionConfig as PlannerMotionConfig;
pub mod hardware;
pub use hardware::*;
pub use krusty_shared::TemperatureController;
pub mod web;
pub mod communication;
pub use communication::*;
pub mod scheduler;
