# printer.toml - Enhanced configuration
[printer]
kinematics = "cartesian"
max_velocity = 300.0
max_accel = 3000.0
max_z_velocity = 25.0
max_z_accel = 100.0
square_corner_velocity = 5.0
bed_size = [200.0, 200.0]
printer_name = "Krusty-RS Printer"

[mcu]
serial = "/dev/ttyUSB0"
baud = 250000
restart_method = "arduino"

[extruder]
step_pin = "PA0"
dir_pin = "PA1"
enable_pin = "PA2"
rotation_distance = 22.67895
gear_ratio = [50.0, 10.0]
microsteps = 16
nozzle_diameter = 0.4
filament_diameter = 1.75
heater_pin = "PA3"
sensor_type = "EPCOS 100K B57560G104F"
sensor_pin = "PA4"
min_temp = 0.0
max_temp = 250.0

[heater_bed]
heater_pin = "PA5"
sensor_type = "EPCOS 100K B57560G104F"
sensor_pin = "PA6"
min_temp = 0.0
max_temp = 130.0
pwm_cycle_time = 0.5

[fans.fan]
pin = "PD0"
max_power = 1.0
shutdown_speed = 0.0

[steppers.stepper_x]
step_pin = "PB0"
dir_pin = "PB1"
enable_pin = "PB2"
rotation_distance = 40.0
microsteps = 16
full_steps_per_rotation = 200
endstop_pin = "PC0"
position_endstop = 0.0
position_min = 0.0
position_max = 200.0
homing_speed = 50.0

[steppers.stepper_y]
step_pin = "PB3"
dir_pin = "PB4"
enable_pin = "PB5"
rotation_distance = 40.0
microsteps = 16
full_steps_per_rotation = 200
endstop_pin = "PC1"
position_endstop = 0.0
position_min = 0.0
position_max = 200.0
homing_speed = 50.0

[steppers.stepper_z]
step_pin = "PC2"
dir_pin = "PC3"
enable_pin = "PC4"
rotation_distance = 8.0
microsteps = 16
full_steps_per_rotation = 200
endstop_pin = "PC5"
position_endstop = 0.0
position_min = 0.0
position_max = 200.0
homing_speed = 25.0

[temperature.hotend]
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114.0

[temperature.bed]
pid_kp = 67.0
pid_ki = 0.8
pid_kd = 1400.0

[motion]
junction_deviation = 0.05
max_jerk = 20.0
acceleration_profile = "trapezoidal"
input_shaping = false

[advanced]
adaptive_motion = false
debug_logging = false